version: '3.9'

services:
  egonsystem:
    build: .
    container_name: streamlit-egonsystem
    ports:
      - "9990:8501"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - STORAGE_BACKEND=local
      - DATALAKE_PATH=/app/data
      - SNAPSHOTS_PATH=/app/data/snapshots
    env_file:
      - .env
